import Phaser from 'phaser';
import { safeShake } from '../systems/AccessibilitySettings';
import { playSound } from '../systems/SoundManager';
import { readGamepad, type GamepadState } from '../systems/GamepadInput';
import {
  PLAYER_SPEED,
  PLAYER_JUMP_VELOCITY,
  PLAYER_MAX_HP,
  PLAYER_MAX_ENERGY,
  PLAYER_ACCEL,
  PLAYER_DECEL,
  PLAYER_AIR_ACCEL,
  PLAYER_AIR_DECEL,
  COYOTE_TIME_MS,
  JUMP_BUFFER_MS,
  INVINCIBILITY_FRAMES_MS,
  HITSTOP_DURATION_MS,
  KNOCKBACK_VELOCITY,
  COLORS,
} from '../../shared/constants';

type GunnerState = 'idle' | 'run' | 'jump' | 'fall' | 'shoot' | 'charge' | 'hurt' | 'dash';

export class Gunner {
  scene: Phaser.Scene;
  sprite: Phaser.Physics.Arcade.Sprite;
  body: Phaser.Physics.Arcade.Body;

  state: GunnerState = 'idle';
  facingRight = true;
  hp: number;
  maxHp: number;
  energy: number;
  maxEnergy: number;
  level = 1;
  xp = 0;
  xpToNext = 100;

  // Combat
  isAttacking = false;
  attackCombo = 0;
  private shootCooldown = 0;
  private chargeTime = 0;
  private isCharging = false;
  private readonly CHARGE_THRESHOLD = 400; // ms to fully charge
  invincibleUntil = 0;
  hitstopUntil = 0;

  // Projectile group
  projectiles: Phaser.Physics.Arcade.Group;

  // Movement
  private coyoteTimeLeft = 0;
  private jumpBuffered = false;
  private jumpBufferTimer = 0;
  private wasOnFloor = false;

  // Dash
  private dashCooldown = 0;
  private isDashing = false;
  private dashTimer = 0;
  private readonly DASH_DURATION = 150;
  private readonly DASH_SPEED = 280;
  private readonly DASH_COOLDOWN = 700;

  // Input
  private cursors!: Phaser.Types.Input.Keyboard.CursorKeys;
  private keys!: {
    attack: Phaser.Input.Keyboard.Key;
    dash: Phaser.Input.Keyboard.Key;
    up: Phaser.Input.Keyboard.Key;
  };

  // Particles
  private dustEmitter: Phaser.GameObjects.Particles.ParticleEmitter;

  // Charge visual
  private chargeIndicator: Phaser.GameObjects.Graphics;

  // Gun barrel aim indicator
  private gunBarrel: Phaser.GameObjects.Sprite;

  // Drop-through platforms
  droppingThrough = false;
  private lastDownPress = 0;
  private readonly DROP_TAP_WINDOW = 250;

  // Gamepad
  private gp: GamepadState | null = null;

  constructor(scene: Phaser.Scene, x: number, y: number) {
    this.scene = scene;
    this.hp = Math.floor(PLAYER_MAX_HP * 0.85); // Gunner has less HP
    this.maxHp = this.hp;
    this.energy = Math.floor(PLAYER_MAX_ENERGY * 1.2); // More energy
    this.maxEnergy = this.energy;

    // Use pixel art texture generated by BootScene
    this.sprite = scene.physics.add.sprite(x, y, 'player-gunner');
    this.sprite.setOrigin(0.5, 1);
    this.body = this.sprite.body as Phaser.Physics.Arcade.Body;
    this.body.setSize(14, 36);
    this.body.setOffset(9, 5);
    this.body.setCollideWorldBounds(true);
    this.body.setMaxVelocityY(600);
    (this.sprite as any).owner = this;

    // Projectile group — uses weapon-gunshot sprite if available
    const projKey = scene.textures.exists('weapon-gunshot') ? 'weapon-gunshot' : 'projectile-player';
    this.projectiles = scene.physics.add.group({
      defaultKey: projKey,
      maxSize: 20,
    });

    // Input (same as Vanguard)
    this.cursors = scene.input.keyboard!.createCursorKeys();
    this.keys = {
      attack: scene.input.keyboard!.addKey(Phaser.Input.Keyboard.KeyCodes.Z),
      dash: scene.input.keyboard!.addKey(Phaser.Input.Keyboard.KeyCodes.X),
      up: scene.input.keyboard!.addKey(Phaser.Input.Keyboard.KeyCodes.UP),
    };

    this.dustEmitter = scene.add.particles(0, 0, 'particle', {
      speed: { min: 10, max: 30 },
      angle: { min: 220, max: 320 },
      scale: { start: 0.8, end: 0 },
      lifespan: 200,
      tint: 0x556677,
      emitting: false,
    });

    this.chargeIndicator = scene.add.graphics();
    this.chargeIndicator.setDepth(15);

    // Gun barrel — shows aim direction at all times
    const barrelKey = scene.textures.exists('weapon-gunbarrel') ? 'weapon-gunbarrel' : 'projectile-player';
    this.gunBarrel = scene.add.sprite(x, y - 16, barrelKey);
    this.gunBarrel.setOrigin(0, 0.5); // Pivot at left edge (shoulder mount)
    this.gunBarrel.setDisplaySize(16, 6);
    this.gunBarrel.setDepth(11);
  }

  update(time: number, delta: number) {
    this.gp = readGamepad(this.scene);
    const onFloor = this.body.onFloor();

    // Hitstop
    if (time < this.hitstopUntil) {
      this.body.setVelocity(0, 0);
      this.body.setAllowGravity(false);
      this.updateGunBarrel(); // Keep barrel attached during freeze
      return;
    }
    this.body.setAllowGravity(true);

    // Invincibility flash
    if (time < this.invincibleUntil) {
      this.sprite.setAlpha(Math.sin(time * 0.02) > 0 ? 1 : 0.3);
    } else {
      this.sprite.setAlpha(1);
    }

    // Landing detection — dust + squash
    if (onFloor && !this.wasOnFloor) {
      // Landing dust burst
      const dust = this.scene.add.particles(this.sprite.x, this.sprite.y, 'particle', {
        speed: { min: 10, max: 30 }, angle: { min: 160, max: 200 },
        scale: { start: 0.5, end: 0 }, lifespan: 200,
        tint: [0x888888, 0xaaaaaa], quantity: 4, emitting: false,
      });
      dust.explode(4);
      this.scene.time.delayedCall(300, () => dust.destroy());

      // Landing squash
      this.scene.tweens.killTweensOf(this.sprite);
      this.sprite.setScale(1.15, 0.85);
      this.scene.tweens.add({ targets: this.sprite, scaleX: 1, scaleY: 1, duration: 120, ease: 'Back.easeOut' });
    }

    // Coyote time
    if (onFloor) this.coyoteTimeLeft = COYOTE_TIME_MS;
    if (!onFloor) this.coyoteTimeLeft = Math.max(0, this.coyoteTimeLeft - delta);
    this.wasOnFloor = onFloor;

    // Jump buffer
    if (this.jumpBuffered) {
      this.jumpBufferTimer -= delta;
      if (this.jumpBufferTimer <= 0) this.jumpBuffered = false;
    }

    // Dash
    if (this.dashCooldown > 0) this.dashCooldown -= delta;
    if (this.isDashing) {
      this.dashTimer -= delta;
      if (this.dashTimer <= 0) {
        this.isDashing = false;
        this.body.setAllowGravity(true);
      } else {
        const dir = this.facingRight ? 1 : -1;
        this.body.setVelocityX(dir * this.DASH_SPEED);
        this.body.setVelocityY(0);
        this.body.setAllowGravity(false);
        this.sprite.setAlpha(0.6);
        this.updateGunBarrel(); // Keep barrel attached during dash
        return;
      }
    }

    if (this.state === 'hurt') {
      this.updateGunBarrel(); // Keep barrel attached during knockback
      return;
    }

    this.handleDropThrough(onFloor);
    this.handleMovement(onFloor, delta);
    this.handleJump(onFloor);
    this.handleShooting(time, delta);
    this.handleDash(time);
    this.updateState(onFloor);

    // Shoot cooldown
    if (this.shootCooldown > 0) this.shootCooldown -= delta;

    // Update charge visual
    this.updateChargeVisual();

    // Update gun barrel aim direction
    this.updateGunBarrel();
  }

  private handleMovement(onFloor: boolean, delta: number) {
    const dt = delta / 1000;
    // Slower while charging — applied to max speed target, not accel rate
    const maxSpeed = PLAYER_SPEED * (this.isCharging ? 0.5 : 1);
    const accel = onFloor ? PLAYER_ACCEL : PLAYER_AIR_ACCEL;
    const decel = onFloor ? PLAYER_DECEL : PLAYER_AIR_DECEL;

    const left = this.cursors.left.isDown || !!this.gp?.left;
    const right = this.cursors.right.isDown || !!this.gp?.right;
    let vx = this.body.velocity.x;

    if (left) {
      vx -= accel * dt;
      if (vx < -maxSpeed) vx = -maxSpeed;
      this.facingRight = false;
      this.sprite.setFlipX(true);
    } else if (right) {
      vx += accel * dt;
      if (vx > maxSpeed) vx = maxSpeed;
      this.facingRight = true;
      this.sprite.setFlipX(false);
    } else {
      // Decelerate toward 0
      if (vx > 0) {
        vx -= decel * dt;
        if (vx < 10) vx = 0;
      } else if (vx < 0) {
        vx += decel * dt;
        if (vx > -10) vx = 0;
      }
    }

    this.body.setVelocityX(vx);
  }

  private handleJump(onFloor: boolean) {
    const jumpPressed = Phaser.Input.Keyboard.JustDown(this.cursors.up) ||
                        Phaser.Input.Keyboard.JustDown(this.keys.up) ||
                        !!this.gp?.jumpJust;
    if (jumpPressed) {
      this.jumpBuffered = true;
      this.jumpBufferTimer = JUMP_BUFFER_MS;
    }
    const canJump = onFloor || this.coyoteTimeLeft > 0;
    if (this.jumpBuffered && canJump) {
      this.body.setVelocityY(PLAYER_JUMP_VELOCITY);
      this.jumpBuffered = false;
      this.coyoteTimeLeft = 0;
      playSound('jump');

      // Jump stretch
      this.scene.tweens.killTweensOf(this.sprite);
      this.sprite.setScale(0.85, 1.15);
      this.scene.tweens.add({ targets: this.sprite, scaleX: 1, scaleY: 1, duration: 150, ease: 'Back.easeOut' });
    }
    if ((this.cursors.up.isUp && this.keys.up.isUp && !this.gp?.jump) && this.body.velocity.y < PLAYER_JUMP_VELOCITY * 0.4) {
      this.body.setVelocityY(this.body.velocity.y * 0.5);
    }
  }

  private handleShooting(time: number, delta: number) {
    // Hold Z/gamepad X to charge, release to fire
    if (this.keys.attack.isDown || this.gp?.attack) {
      if (!this.isCharging && this.shootCooldown <= 0) {
        this.isCharging = true;
        this.chargeTime = 0;
      }
      if (this.isCharging) {
        this.chargeTime += delta;
      }
    }

    // Release: keyboard JustUp OR gamepad button just released
    if ((Phaser.Input.Keyboard.JustUp(this.keys.attack) || this.gp?.attackReleased) && this.isCharging) {
      this.fireProjectile(time);
      this.isCharging = false;
      this.chargeTime = 0;
    }

    // Quick tap = instant shot
    if (Phaser.Input.Keyboard.JustDown(this.keys.attack) && this.shootCooldown <= 0 && !this.isCharging) {
      // Will be handled on release or next frame
    }
  }

  /** Get aim direction based on arrow keys / gamepad — supports 8-directional aiming */
  private getAimDirection(): { x: number; y: number } {
    const up = this.cursors.up.isDown || !!this.gp?.up;
    const down = this.cursors.down.isDown || !!this.gp?.down;
    const left = this.cursors.left.isDown || !!this.gp?.left;
    const right = this.cursors.right.isDown || !!this.gp?.right;
    const dirX = this.facingRight ? 1 : -1;

    if (up && !down) {
      if (!left && !right) return { x: 0, y: -1 }; // Straight up
      return { x: dirX * 0.707, y: -0.707 }; // Diagonal up
    }
    if (down && !up) {
      const onFloor = this.body.onFloor();
      if (!left && !right && !onFloor) return { x: 0, y: 1 }; // Straight down (airborne)
      return { x: dirX * 0.707, y: 0.707 }; // Diagonal down
    }
    return { x: dirX, y: 0 }; // Horizontal (default)
  }

  private fireProjectile(_time: number) {
    const isCharged = this.chargeTime >= this.CHARGE_THRESHOLD;
    const aim = this.getAimDirection();

    // Spawn position offset in aim direction
    const spawnOffX = aim.x * 12;
    const spawnOffY = -16 + aim.y * 8;

    const proj = this.projectiles.get(
      this.sprite.x + spawnOffX,
      this.sprite.y + spawnOffY,
      'projectile-player'
    ) as Phaser.Physics.Arcade.Sprite;

    if (!proj) return;
    proj.setActive(true).setVisible(true);
    proj.body!.enable = true;

    const projBody = proj.body as Phaser.Physics.Arcade.Body;
    projBody.setAllowGravity(false);

    // Rotate projectile to match aim direction
    proj.setRotation(Math.atan2(aim.y, aim.x));

    // Stat scaling: +4% ranged damage per precision above 5
    const inv = (this.scene as any).getInventory?.();
    let precisionMult = 1;
    let rangedBonus = 0;
    if (inv) {
      const precision = inv.getEffectiveStat('precision');
      precisionMult = 1 + (precision - 5) * 0.04;
      rangedBonus = inv.getSkillEffect('rangedDamageBonus') || 0;
    }

    // Shot speed scales with precision and level
    // Base: 160 normal / 200 charged → up to ~250/310 at high levels
    const speedBonus = 1 + (this.level - 1) * 0.03; // +3% per level
    let shotSpeedMult = speedBonus;
    if (inv) {
      const precision = inv.getEffectiveStat('precision');
      shotSpeedMult += (precision - 5) * 0.02; // +2% per precision above 5
    }

    if (isCharged) {
      // Charge shot: bigger, faster, pierces — use charged texture
      playSound('chargedShot');
      const chargeKey = this.scene.textures.exists('weapon-chargeshot') ? 'weapon-chargeshot' : undefined;
      if (chargeKey) proj.setTexture(chargeKey);
      proj.setDisplaySize(14, 8);
      const chargeSpeed = Math.round(200 * shotSpeedMult);
      projBody.setVelocity(aim.x * chargeSpeed, aim.y * chargeSpeed);
      proj.setTint(0x00ffcc);
      let chargeDmg = Math.round(12 * precisionMult * (1 + rangedBonus));
      // Skill: overchargeDamageBonus — extra damage for charged shots
      if (inv) {
        const overcharge = inv.getSkillEffect('overchargeDamageBonus');
        if (overcharge) chargeDmg = Math.round(chargeDmg * (1 + overcharge));
      }
      (proj as any).damage = chargeDmg;
      (proj as any).piercing = true;
    } else {
      // Normal shot
      playSound('gunShot');
      proj.setDisplaySize(8, 4);
      const normalSpeed = Math.round(160 * shotSpeedMult);
      projBody.setVelocity(aim.x * normalSpeed, aim.y * normalSpeed);
      proj.clearTint();
      (proj as any).damage = Math.round(8 * precisionMult * (1 + rangedBonus));
      (proj as any).piercing = false;
    }

    (proj as any).isPlayerProjectile = true;
    // Fire rate improves with level — 2% faster per level, min 60% of base
    const cdMult = Math.max(0.6, 1 - (this.level - 1) * 0.02);
    this.shootCooldown = (isCharged ? 400 : 200) * cdMult;

    // Auto-destroy after 2 seconds
    this.scene.time.delayedCall(2000, () => {
      if (proj.active) {
        proj.setActive(false).setVisible(false);
        proj.body!.enable = false;
      }
    });

    // Recoil opposite to aim direction
    const recoilX = aim.x !== 0 ? -aim.x * 30 : 0;
    this.body.setVelocityX(this.body.velocity.x + recoilX);

    // Muzzle flash particles
    const projX = this.sprite.x + spawnOffX;
    const projY = this.sprite.y + spawnOffY;
    const dir = aim.x >= 0 ? 1 : -1;
    const muzzle = this.scene.add.particles(projX, projY, 'particle', {
      speed: { min: 20, max: 60 }, angle: { min: dir > 0 ? -30 : 150, max: dir > 0 ? 30 : 210 },
      scale: { start: 0.8, end: 0 }, lifespan: 100,
      tint: [0x44ff88, 0xffffff], quantity: 5, emitting: false,
    });
    muzzle.explode(5);
    this.scene.time.delayedCall(200, () => muzzle.destroy());

    this.isAttacking = true;
    this.scene.time.delayedCall(150, () => { this.isAttacking = false; });
  }

  private handleDropThrough(onFloor: boolean) {
    const downJust = Phaser.Input.Keyboard.JustDown(this.cursors.down) || !!this.gp?.downJust;
    if (downJust && onFloor) {
      const now = this.scene.time.now;
      if (now - this.lastDownPress < this.DROP_TAP_WINDOW) {
        this.droppingThrough = true;
        this.body.setVelocityY(40);
        this.scene.time.delayedCall(200, () => { this.droppingThrough = false; });
        this.lastDownPress = 0;
      } else {
        this.lastDownPress = now;
      }
    }
  }

  private handleDash(time: number) {
    if (!Phaser.Input.Keyboard.JustDown(this.keys.dash) && !this.gp?.dashJust) return;
    if (this.dashCooldown > 0 || this.isDashing) return;
    this.isDashing = true;
    this.dashTimer = this.DASH_DURATION;
    this.dashCooldown = this.DASH_COOLDOWN;
    this.invincibleUntil = Math.max(this.invincibleUntil, time + this.DASH_DURATION);
  }

  private updateChargeVisual() {
    this.chargeIndicator.clear();
    if (!this.isCharging) return;

    const ratio = Math.min(1, this.chargeTime / this.CHARGE_THRESHOLD);
    const aim = this.getAimDirection();
    const x = this.sprite.x + aim.x * 10;
    const y = this.sprite.y - 16 + aim.y * 6;

    if (ratio >= 1) {
      // Fully charged — glow
      this.chargeIndicator.fillStyle(COLORS.neon, 0.6 + Math.sin(Date.now() * 0.01) * 0.3);
      this.chargeIndicator.fillCircle(x, y, 4);
    } else {
      // Charging — growing circle
      this.chargeIndicator.lineStyle(1, COLORS.neon, ratio);
      this.chargeIndicator.strokeCircle(x, y, 2 + ratio * 3);
    }
  }

  private updateGunBarrel() {
    const aim = this.getAimDirection();
    // Position barrel at the character's arm/shoulder area
    const mountX = this.sprite.x + (this.facingRight ? 4 : -4);
    const mountY = this.sprite.y - 18;
    this.gunBarrel.setPosition(mountX, mountY);

    // Rotate to match aim direction
    const angle = Math.atan2(aim.y, aim.x);
    this.gunBarrel.setRotation(angle);

    // Flip vertically when facing left so the barrel doesn't render upside-down
    this.gunBarrel.setFlipY(!this.facingRight);

    // Subtle glow when charging — teal→cyan ramp
    if (this.isCharging) {
      const ratio = Math.min(1, this.chargeTime / this.CHARGE_THRESHOLD);
      this.gunBarrel.setTint(Phaser.Display.Color.GetColor(
        0, Math.round(0xaa + ratio * 0x55), Math.round(0x66 + ratio * 0x99)
      ));
    } else {
      this.gunBarrel.clearTint();
    }
  }

  private updateState(onFloor: boolean) {
    if (this.isDashing) this.state = 'dash';
    else if (this.isCharging) this.state = 'charge';
    else if (this.isAttacking) this.state = 'shoot';
    else if (!onFloor && this.body.velocity.y < 0) this.state = 'jump';
    else if (!onFloor && this.body.velocity.y > 0) this.state = 'fall';
    else if (Math.abs(this.body.velocity.x) > 10) this.state = 'run';
    else this.state = 'idle';
  }

  takeDamage(amount: number, sourceX: number, time: number) {
    if (time < this.invincibleUntil) return;
    // Vitality damage reduction: -2% per vitality above 5, capped at 40%
    const inv = (this.scene as any).getInventory?.();
    const vitality = inv ? inv.getEffectiveStat('vitality') : 5;
    const reduction = Math.min(0.4, Math.max(0, (vitality - 5) * 0.02));
    const finalDmg = Math.max(1, Math.round(amount * (1 - reduction)));

    this.hp = Math.max(0, this.hp - finalDmg);
    playSound('playerHurt');
    this.invincibleUntil = time + INVINCIBILITY_FRAMES_MS;
    this.hitstopUntil = time + HITSTOP_DURATION_MS;
    const dir = this.sprite.x < sourceX ? -1 : 1;
    this.body.setVelocityX(dir * KNOCKBACK_VELOCITY);
    this.body.setVelocityY(-120);
    safeShake(this.scene.cameras.main, 100, 0.01);
    this.sprite.setTint(0xff4444);
    this.scene.time.delayedCall(100, () => { if (this.sprite.active) this.sprite.clearTint(); });
    this.state = 'hurt';
    this.scene.time.delayedCall(300, () => {
      if (this.state === 'hurt') this.state = 'idle';
    });
    if (this.hp <= 0) { playSound('playerDeath'); this.die(); }
  }

  onAttackHit(time: number) {
    this.hitstopUntil = time + HITSTOP_DURATION_MS * 0.5;
    this.gainEnergy(2);
    playSound('enemyHit');
  }

  gainXP(amount: number) {
    this.xp += amount;
    if (this.xp >= this.xpToNext) {
      this.xp -= this.xpToNext;
      this.level++;
      this.xpToNext = Math.floor(this.xpToNext * 1.3);
      const inv = (this.scene as any).getInventory?.();
      const vitalityBonus = inv ? Math.max(0, inv.getEffectiveStat('vitality') - 5) * 2 : 0;
      this.maxHp += 6 + vitalityBonus;
      this.hp = this.maxHp;
      this.maxEnergy += 4;
      this.energy = this.maxEnergy;
      (this.scene as any).onPlayerLevelUp?.();
    }
  }

  gainEnergy(amount: number) {
    this.energy = Math.min(this.maxEnergy, this.energy + amount);
  }

  /** Clean up all owned game objects */
  destroy() {
    this.chargeIndicator.destroy();
    this.dustEmitter.destroy();
    this.gunBarrel.destroy();
    this.projectiles.destroy(true);
  }

  private die() {
    const gameScene = this.scene as any;
    if (gameScene.onPlayerDeath) {
      gameScene.onPlayerDeath();
    }
  }

  getAttackHitbox(): Phaser.Geom.Rectangle | null { return null; } // Gunner uses projectiles
  getAttackDamage(): number { return 0; }

  /** Weak-point (headshot) damage multiplier — base 1.5×, scales with skills */
  getWeakPointBonus(): number {
    let mult = 1.5;
    const inv = (this.scene as any).getInventory?.();
    if (inv) {
      const bonus = inv.getSkillEffect('weakPointBonus');
      if (bonus) mult += bonus; // e.g. +0.25 from skill tree
    }
    return mult;
  }
}
