import Phaser from 'phaser';
import { safeShake } from '../systems/AccessibilitySettings';
import { playSound } from '../systems/SoundManager';
import { readGamepad, type GamepadState } from '../systems/GamepadInput';
import {
  PLAYER_SPEED,
  PLAYER_JUMP_VELOCITY,
  PLAYER_MAX_HP,
  PLAYER_MAX_ENERGY,
  PLAYER_ACCEL,
  PLAYER_DECEL,
  PLAYER_AIR_ACCEL,
  PLAYER_AIR_DECEL,
  COYOTE_TIME_MS,
  JUMP_BUFFER_MS,
  INVINCIBILITY_FRAMES_MS,
  HITSTOP_DURATION_MS,
  KNOCKBACK_VELOCITY,
  COLORS,
} from '../../shared/constants';

type WraithState = 'idle' | 'run' | 'jump' | 'fall' | 'attack' | 'hurt' | 'dash' | 'wallcling';

export class Wraith {
  scene: Phaser.Scene;
  sprite: Phaser.Physics.Arcade.Sprite;
  body: Phaser.Physics.Arcade.Body;

  state: WraithState = 'idle';
  facingRight = true;
  hp: number;
  maxHp: number;
  energy: number;
  maxEnergy: number;
  level = 1;
  xp = 0;
  xpToNext = 100;

  // Combat — fast twin daggers
  isAttacking = false;
  attackCombo = 0; // 0-3 for 4-hit flurry
  private attackTimer = 0;
  private attackCooldown = 0;
  slashSprite: Phaser.GameObjects.Sprite | null = null;
  invincibleUntil = 0;
  hitstopUntil = 0;

  // Crit system
  private critChance = 0.2; // 20% base crit
  private critMultiplier = 1.8;
  private lastHitWasCrit = false;

  // Backstab system — extra damage when attacking from behind
  private readonly BACKSTAB_MULTIPLIER = 1.6;
  private lastHitWasBackstab = false;

  // Poison — applied on 4th combo hit (finisher)
  private readonly POISON_DURATION = 3000; // 3 seconds
  private readonly POISON_SLOW = 0.4; // 60% slow

  // Movement — Wraith is fastest
  private readonly WRAITH_SPEED = PLAYER_SPEED * 1.25;
  private readonly WRAITH_JUMP = PLAYER_JUMP_VELOCITY * 1.1;
  private coyoteTimeLeft = 0;
  private jumpBuffered = false;
  private jumpBufferTimer = 0;
  private wasOnFloor = false;

  // Double jump (Wraith exclusive mobility)
  private hasDoubleJump = true;

  // Wall cling (Wraith starts with this!)
  private isTouchingWall = false;
  private wallDir = 0; // -1 left, 1 right
  private wallSlideSpeed = 30;

  // Dash — Wraith dash is faster and shorter
  private dashCooldown = 0;
  private isDashing = false;
  private dashTimer = 0;
  private readonly DASH_DURATION = 120;
  private readonly DASH_SPEED = 350;
  private readonly DASH_COOLDOWN = 500;

  // Afterimage effect
  private afterimages: Phaser.GameObjects.Sprite[] = [];

  // Ultimate ability — Shadow Strike
  private ultimateCooldownUntil = 0;
  private readonly ULTIMATE_COOLDOWN = 8000;
  private readonly ULTIMATE_ENERGY_COST = 40;

  // Input
  private cursors!: Phaser.Types.Input.Keyboard.CursorKeys;
  private keys!: {
    attack: Phaser.Input.Keyboard.Key;
    dash: Phaser.Input.Keyboard.Key;
    up: Phaser.Input.Keyboard.Key;
    ultimate: Phaser.Input.Keyboard.Key;
  };

  private dustEmitter: Phaser.GameObjects.Particles.ParticleEmitter;
  private critEmitter: Phaser.GameObjects.Particles.ParticleEmitter;

  // Drop-through platforms
  droppingThrough = false;
  private lastDownPress = 0;
  private readonly DROP_TAP_WINDOW = 250;

  // Gamepad
  private gp: GamepadState | null = null;

  constructor(scene: Phaser.Scene, x: number, y: number) {
    this.scene = scene;
    this.hp = Math.floor(PLAYER_MAX_HP * 0.7); // Lowest HP
    this.maxHp = this.hp;
    this.energy = PLAYER_MAX_ENERGY;
    this.maxEnergy = this.energy;

    // Use pixel art texture generated by BootScene
    this.sprite = scene.physics.add.sprite(x, y, 'player-wraith');
    this.sprite.setOrigin(0.5, 1);
    this.body = this.sprite.body as Phaser.Physics.Arcade.Body;
    this.body.setSize(12, 36);
    this.body.setOffset(14, 5);
    this.body.setCollideWorldBounds(true);
    this.body.setMaxVelocityY(600);
    (this.sprite as any).owner = this;

    this.cursors = scene.input.keyboard!.createCursorKeys();
    this.keys = {
      attack: scene.input.keyboard!.addKey(Phaser.Input.Keyboard.KeyCodes.Z),
      dash: scene.input.keyboard!.addKey(Phaser.Input.Keyboard.KeyCodes.X),
      up: scene.input.keyboard!.addKey(Phaser.Input.Keyboard.KeyCodes.UP),
      ultimate: scene.input.keyboard!.addKey(Phaser.Input.Keyboard.KeyCodes.V),
    };

    this.dustEmitter = scene.add.particles(0, 0, 'particle', {
      speed: { min: 10, max: 30 },
      angle: { min: 220, max: 320 },
      scale: { start: 0.8, end: 0 },
      lifespan: 200,
      tint: 0x8844cc,
      emitting: false,
    });

    this.critEmitter = scene.add.particles(0, 0, 'particle-hit', {
      speed: { min: 60, max: 120 },
      angle: { min: 0, max: 360 },
      scale: { start: 1.2, end: 0 },
      lifespan: 200,
      tint: 0xffcc00,
      emitting: false,
    });
  }

  update(time: number, delta: number) {
    this.gp = readGamepad(this.scene);
    const onFloor = this.body.onFloor();

    // Hitstop
    if (time < this.hitstopUntil) {
      this.body.setVelocity(0, 0);
      this.body.setAllowGravity(false);
      return;
    }
    this.body.setAllowGravity(true);

    // Invincibility flash
    if (time < this.invincibleUntil) {
      this.sprite.setAlpha(Math.sin(time * 0.025) > 0 ? 1 : 0.2);
    } else {
      this.sprite.setAlpha(1);
    }

    // Coyote time
    if (onFloor) this.coyoteTimeLeft = COYOTE_TIME_MS;
    if (!onFloor) this.coyoteTimeLeft = Math.max(0, this.coyoteTimeLeft - delta);

    // Jump buffer
    if (this.jumpBuffered) {
      this.jumpBufferTimer -= delta;
      if (this.jumpBufferTimer <= 0) this.jumpBuffered = false;
    }

    // Attack timer
    if (this.attackCooldown > 0) this.attackCooldown -= delta;
    if (this.isAttacking) {
      this.attackTimer -= delta;
      if (this.attackTimer <= 0) this.endAttack();
      else this.updateSlashPosition();
    }

    // Dash
    if (this.dashCooldown > 0) this.dashCooldown -= delta;
    if (this.isDashing) {
      this.dashTimer -= delta;
      if (this.dashTimer <= 0) {
        this.isDashing = false;
        this.body.setAllowGravity(true);
      } else {
        const dir = this.facingRight ? 1 : -1;
        this.body.setVelocityX(dir * this.DASH_SPEED);
        this.body.setVelocityY(0);
        this.body.setAllowGravity(false);
        this.spawnAfterimage();
        return;
      }
    }

    // Wall cling check
    this.checkWallCling(onFloor);

    if (this.state === 'hurt') return;

    this.handleDropThrough(onFloor);
    this.handleMovement(onFloor, delta);
    this.handleJump(onFloor);
    this.handleAttack(time);
    this.handleDash(time);
    this.handleUltimate(time);
    this.updateState(onFloor);

    // Landing dust + reset double jump + squash
    if (onFloor && !this.wasOnFloor) {
      this.dustEmitter.emitParticleAt(this.sprite.x, this.sprite.y, 4);
      // Landing dust burst
      const dust = this.scene.add.particles(this.sprite.x, this.sprite.y, 'particle', {
        speed: { min: 10, max: 30 }, angle: { min: 160, max: 200 },
        scale: { start: 0.5, end: 0 }, lifespan: 200,
        tint: [0x888888, 0xaaaaaa], quantity: 4, emitting: false,
      });
      dust.explode(4);
      this.scene.time.delayedCall(300, () => dust.destroy());
      // Squash on land
      this.scene.tweens.killTweensOf(this.sprite);
      this.sprite.setScale(1.15, 0.85);
      this.scene.tweens.add({ targets: this.sprite, scaleX: 1, scaleY: 1, duration: 120, ease: 'Back.easeOut' });
      this.hasDoubleJump = true;
    }
    this.wasOnFloor = onFloor;

    // Afterimage cleanup
    this.afterimages = this.afterimages.filter(img => {
      if (img.alpha <= 0.05) { img.destroy(); return false; }
      return true;
    });
  }

  private checkWallCling(onFloor: boolean) {
    if (onFloor) { this.isTouchingWall = false; return; }

    this.isTouchingWall = this.body.blocked.left || this.body.blocked.right;
    if (this.isTouchingWall) {
      this.wallDir = this.body.blocked.left ? -1 : 1;
      // Slow fall while on wall
      if (this.body.velocity.y > this.wallSlideSpeed) {
        this.body.setVelocityY(this.wallSlideSpeed);
      }
    }
  }

  private handleMovement(onFloor: boolean, delta: number) {
    if (this.isAttacking && onFloor) {
      this.body.setVelocityX(this.body.velocity.x * 0.85);
      return;
    }

    const dt = delta / 1000;
    const left = this.cursors.left.isDown || !!this.gp?.left;
    const right = this.cursors.right.isDown || !!this.gp?.right;

    const accel = onFloor ? PLAYER_ACCEL * 1.2 : PLAYER_AIR_ACCEL * 1.2;
    const decel = onFloor ? PLAYER_DECEL : PLAYER_AIR_DECEL;
    let vx = this.body.velocity.x;

    if (left) {
      vx -= accel * dt;
      if (vx < -this.WRAITH_SPEED) vx = -this.WRAITH_SPEED;
      this.facingRight = false;
      this.sprite.setFlipX(true);
    } else if (right) {
      vx += accel * dt;
      if (vx > this.WRAITH_SPEED) vx = this.WRAITH_SPEED;
      this.facingRight = true;
      this.sprite.setFlipX(false);
    } else {
      // Decelerate toward 0
      if (vx > 0) {
        vx -= decel * dt;
        if (vx < 10) vx = 0;
      } else if (vx < 0) {
        vx += decel * dt;
        if (vx > -10) vx = 0;
      }
    }

    this.body.setVelocityX(vx);
  }

  private handleJump(onFloor: boolean) {
    const jumpPressed = Phaser.Input.Keyboard.JustDown(this.cursors.up) ||
                        Phaser.Input.Keyboard.JustDown(this.keys.up) ||
                        !!this.gp?.jumpJust;
    if (jumpPressed) {
      this.jumpBuffered = true;
      this.jumpBufferTimer = JUMP_BUFFER_MS;
    }

    // Wall jump!
    if (this.jumpBuffered && this.isTouchingWall && !onFloor) {
      this.body.setVelocityY(this.WRAITH_JUMP);
      this.body.setVelocityX(-this.wallDir * this.WRAITH_SPEED); // Jump away from wall
      this.jumpBuffered = false;
      this.isTouchingWall = false;
      this.hasDoubleJump = true; // Wall jump resets double jump
      this.facingRight = this.wallDir < 0;
      this.sprite.setFlipX(!this.facingRight);
      this.dustEmitter.emitParticleAt(this.sprite.x, this.sprite.y - 10, 3);
      // Stretch on wall jump
      this.scene.tweens.killTweensOf(this.sprite);
      this.sprite.setScale(0.85, 1.15);
      this.scene.tweens.add({ targets: this.sprite, scaleX: 1, scaleY: 1, duration: 150, ease: 'Back.easeOut' });
      playSound('wallJump');
      return;
    }

    const canJump = onFloor || this.coyoteTimeLeft > 0;
    if (this.jumpBuffered && canJump) {
      this.body.setVelocityY(this.WRAITH_JUMP);
      this.jumpBuffered = false;
      this.coyoteTimeLeft = 0;
      this.hasDoubleJump = true; // Reset double jump on ground jump
      // Stretch on ground jump
      this.scene.tweens.killTweensOf(this.sprite);
      this.sprite.setScale(0.85, 1.15);
      this.scene.tweens.add({ targets: this.sprite, scaleX: 1, scaleY: 1, duration: 150, ease: 'Back.easeOut' });
      playSound('jump');
      return;
    }

    // Double jump (air only, once per grounding)
    if (this.jumpBuffered && !onFloor && this.hasDoubleJump && !this.isTouchingWall) {
      this.body.setVelocityY(this.WRAITH_JUMP * 0.85); // Slightly weaker than ground jump
      this.jumpBuffered = false;
      this.hasDoubleJump = false;
      // Visual feedback: burst of particles + stretch
      this.dustEmitter.emitParticleAt(this.sprite.x, this.sprite.y, 5);
      this.scene.tweens.killTweensOf(this.sprite);
      this.sprite.setScale(0.85, 1.15);
      this.scene.tweens.add({ targets: this.sprite, scaleX: 1, scaleY: 1, duration: 150, ease: 'Back.easeOut' });
      playSound('doubleJump');
    }

    // Variable jump height
    if ((this.cursors.up.isUp && this.keys.up.isUp && !this.gp?.jump) && this.body.velocity.y < this.WRAITH_JUMP * 0.4) {
      this.body.setVelocityY(this.body.velocity.y * 0.5);
    }
  }

  private handleAttack(time: number) {
    if (!Phaser.Input.Keyboard.JustDown(this.keys.attack) && !this.gp?.attackJust) return;
    if (this.attackCooldown > 0 || this.isDashing) return;
    this.startAttack(time);
  }

  private startAttack(_time: number) {
    this.isAttacking = true;

    if (this.attackCombo < 3 && this.attackTimer > -150) {
      this.attackCombo++;
    } else {
      this.attackCombo = 0;
    }

    // Wraith attacks are very fast
    const durations = [100, 90, 80, 200]; // 4th hit is the finisher
    this.attackTimer = durations[this.attackCombo];
    this.attackCooldown = 50; // Very low — encourages rapid mashing

    this.createSlash();
    playSound('swordSwing');
  }

  // Arc slash animation state
  private slashArcProgress = 0; // 0→1 over the attack duration
  private slashArcDuration = 0;

  private createSlash() {
    if (this.slashSprite) this.slashSprite.destroy();

    const textureKey = this.scene.textures.exists('weapon-dagger-arc') ? 'weapon-dagger-arc' : 'slash';
    this.slashSprite = this.scene.add.sprite(
      this.sprite.x,
      this.sprite.y - 20,
      textureKey
    );

    // Larger, more visible slash
    const sizes = [
      { w: 22, h: 10 },
      { w: 24, h: 12 },
      { w: 22, h: 10 },
      { w: 30, h: 14 }, // Finisher — big arc
    ];
    const size = sizes[this.attackCombo];
    this.slashSprite.setDisplaySize(size.w, size.h);
    this.slashSprite.setAlpha(0.85);
    this.slashSprite.setTint(COLORS.wraith);
    this.slashSprite.setDepth(10);

    // Arc animation: track progress through the swing
    this.slashArcProgress = 0;
    const durations = [100, 90, 80, 200];
    this.slashArcDuration = durations[this.attackCombo];

    // Small forward lunge on each hit
    const dir = this.facingRight ? 1 : -1;
    this.body.setVelocityX(dir * 40);

    // Position at start of arc
    this.updateSlashPosition();
  }

  private updateSlashPosition() {
    if (!this.slashSprite) return;
    const dir = this.facingRight ? 1 : -1;

    // Arc progress: 0 = start (low-front), 1 = end (high-behind or low again)
    // Advance progress based on remaining attack time
    const durations = [100, 90, 80, 200];
    const totalDur = durations[this.attackCombo];
    this.slashArcProgress = Math.min(1, 1 - (this.attackTimer / totalDur));

    // Arc path: starts straight ahead (0°), sweeps upward (~100°)
    // Mashing attack hits forward; upswing catches enemies above
    // Even combos (0,2): tight forward→up    Odd combos (1,3): slightly lower start→higher end
    const t = this.slashArcProgress;
    let arcAngle: number;
    let radius: number;

    if (this.attackCombo % 2 === 0) {
      // Forward → up: 0° to 100°
      arcAngle = (t * 100) * (Math.PI / 180);
      radius = 18;
    } else {
      // Slight dip forward → up: -10° to 110°
      arcAngle = (-10 + t * 120) * (Math.PI / 180);
      radius = 20;
    }

    // Position along arc centered on player shoulder
    const pivotX = this.sprite.x;
    const pivotY = this.sprite.y - 20; // Shoulder height
    const slashX = pivotX + dir * Math.cos(arcAngle) * radius;
    const slashY = pivotY - Math.sin(arcAngle) * radius;

    this.slashSprite.setPosition(slashX, slashY);
    // Rotate sprite to follow arc tangent
    const visualAngle = dir > 0 ? -arcAngle : Math.PI + arcAngle;
    this.slashSprite.setRotation(visualAngle);
    this.slashSprite.setFlipY(!this.facingRight);
  }

  private endAttack() {
    this.isAttacking = false;
    if (this.slashSprite) {
      this.slashSprite.destroy();
      this.slashSprite = null;
    }
    this.scene.time.delayedCall(250, () => {
      if (!this.isAttacking) this.attackCombo = 0;
    });
  }

  private handleDropThrough(onFloor: boolean) {
    const downJust = Phaser.Input.Keyboard.JustDown(this.cursors.down) || !!this.gp?.downJust;
    if (downJust && onFloor) {
      const now = this.scene.time.now;
      if (now - this.lastDownPress < this.DROP_TAP_WINDOW) {
        this.droppingThrough = true;
        this.body.setVelocityY(40);
        this.scene.time.delayedCall(200, () => { this.droppingThrough = false; });
        this.lastDownPress = 0;
      } else {
        this.lastDownPress = now;
      }
    }
  }

  private handleDash(time: number) {
    if (!Phaser.Input.Keyboard.JustDown(this.keys.dash) && !this.gp?.dashJust) return;
    if (this.dashCooldown > 0 || this.isDashing) return;
    this.isDashing = true;
    this.dashTimer = this.DASH_DURATION;
    this.dashCooldown = this.DASH_COOLDOWN;
    this.invincibleUntil = Math.max(this.invincibleUntil, time + this.DASH_DURATION);
    playSound('dash');
  }

  /** Ultimate: Shadow Strike — teleport to nearest enemy, backstab, invincible 0.5s */
  private handleUltimate(time: number) {
    if (!Phaser.Input.Keyboard.JustDown(this.keys.ultimate)) return;
    if (time < this.ultimateCooldownUntil) return;
    if (this.energy < this.ULTIMATE_ENERGY_COST) return;
    if (this.isDashing) return;

    // Find nearest enemy within 200px
    const gameScene = this.scene as any;
    const enemies = gameScene.enemies as any[] | undefined;
    const boss = gameScene.boss;
    let nearest: any = null;
    let nearestDist = 200;

    if (enemies) {
      for (const enemy of enemies) {
        if (!enemy?.sprite?.active) continue;
        const dist = Phaser.Math.Distance.Between(
          this.sprite.x, this.sprite.y,
          enemy.sprite.x, enemy.sprite.y
        );
        if (dist < nearestDist) {
          nearestDist = dist;
          nearest = enemy;
        }
      }
    }

    // Also check boss
    if (boss?.sprite?.active && boss.state !== 'dead') {
      const dist = Phaser.Math.Distance.Between(
        this.sprite.x, this.sprite.y,
        boss.sprite.x, boss.sprite.y
      );
      if (dist < nearestDist) {
        nearestDist = dist;
        nearest = boss;
      }
    }

    if (!nearest) return; // No valid target — don't consume resources

    this.energy -= this.ULTIMATE_ENERGY_COST;
    this.ultimateCooldownUntil = time + this.ULTIMATE_COOLDOWN;

    playSound('powerAbsorb');
    this.scene.cameras.main.flash(60, 80, 0, 160);

    // Spawn afterimage at current position
    this.spawnAfterimage();

    // Teleport behind the target
    const behindOffset = nearest.sprite.x > this.sprite.x ? -20 : 20;
    this.sprite.setPosition(nearest.sprite.x + behindOffset, nearest.sprite.y);
    this.facingRight = behindOffset < 0;
    this.sprite.setFlipX(!this.facingRight);

    // Deal backstab damage
    if (nearest.takeDamage) {
      nearest.takeDamage(25, this.sprite.x, time);
    }

    // Particle burst at arrival
    this.dustEmitter.emitParticleAt(this.sprite.x, this.sprite.y, 8);

    // Brief invincibility
    this.invincibleUntil = Math.max(this.invincibleUntil, time + 500);
  }

  private spawnAfterimage() {
    const img = this.scene.add.sprite(this.sprite.x, this.sprite.y, 'player-wraith');
    img.setOrigin(0.5, 1);
    img.setAlpha(0.4);
    img.setTint(COLORS.wraith);
    img.setFlipX(this.sprite.flipX);
    this.scene.tweens.add({
      targets: img,
      alpha: 0,
      duration: 200,
    });
    this.afterimages.push(img);
  }

  private updateState(onFloor: boolean) {
    if (this.isDashing) this.state = 'dash';
    else if (this.isTouchingWall && !onFloor) this.state = 'wallcling';
    else if (this.isAttacking) this.state = 'attack';
    else if (!onFloor && this.body.velocity.y < 0) this.state = 'jump';
    else if (!onFloor && this.body.velocity.y > 0) this.state = 'fall';
    else if (Math.abs(this.body.velocity.x) > 10) this.state = 'run';
    else this.state = 'idle';
  }

  takeDamage(amount: number, sourceX: number, time: number) {
    if (time < this.invincibleUntil) return;

    // Vitality damage reduction: -2% per vitality above 5, capped at 40%
    const inv = (this.scene as any).getInventory?.();
    const vitality = inv ? inv.getEffectiveStat('vitality') : 5;
    const reduction = Math.min(0.4, Math.max(0, (vitality - 5) * 0.02));
    const finalDmg = Math.max(1, Math.round(amount * (1 - reduction)));

    this.hp = Math.max(0, this.hp - finalDmg);
    playSound('playerHurt');
    this.invincibleUntil = time + INVINCIBILITY_FRAMES_MS;
    this.hitstopUntil = time + HITSTOP_DURATION_MS;
    const dir = this.sprite.x < sourceX ? -1 : 1;
    this.body.setVelocityX(dir * KNOCKBACK_VELOCITY * 1.2); // Wraith gets knocked further
    this.body.setVelocityY(-120);
    safeShake(this.scene.cameras.main, 100, 0.01);
    this.sprite.setTint(0xff4444);
    this.scene.time.delayedCall(100, () => { if (this.sprite.active) this.sprite.clearTint(); });
    this.state = 'hurt';
    this.scene.time.delayedCall(250, () => {
      if (this.state === 'hurt') this.state = 'idle';
    });
    if (this.hp <= 0) { playSound('playerDeath'); this.die(); }
  }

  onAttackHit(time: number) {
    this.hitstopUntil = time + HITSTOP_DURATION_MS * 0.6; // Shorter hitstop for fast attacks
    safeShake(this.scene.cameras.main, 30, 0.003);

    // Crit check — base crit + skill bonuses
    const inv = (this.scene as any).getInventory?.();
    const skillCritBonus = inv ? inv.getSkillEffect('critChanceBonus') : 0;
    this.lastHitWasCrit = Math.random() < (this.critChance + skillCritBonus);
    if (this.lastHitWasCrit) {
      this.critEmitter.emitParticleAt(this.sprite.x + (this.facingRight ? 15 : -15), this.sprite.y - 10, 6);
      safeShake(this.scene.cameras.main, 60, 0.008);
      playSound('critHit');
    } else {
      playSound('swordHit');
    }

    // Backstab feedback — purple flash
    if (this.lastHitWasBackstab) {
      this.critEmitter.emitParticleAt(this.sprite.x + (this.facingRight ? 15 : -15), this.sprite.y - 14, 4);
      this.lastHitWasBackstab = false;
      playSound('backstab');
    }

    this.gainEnergy(this.lastHitWasCrit ? 4 : 2); // Crits give more energy
  }

  gainXP(amount: number) {
    this.xp += amount;
    if (this.xp >= this.xpToNext) {
      this.xp -= this.xpToNext;
      this.level++;
      this.xpToNext = Math.floor(this.xpToNext * 1.3);
      const inv = (this.scene as any).getInventory?.();
      const vitalityBonus = inv ? Math.max(0, inv.getEffectiveStat('vitality') - 5) * 2 : 0;
      this.maxHp += 5 + vitalityBonus;
      this.hp = this.maxHp;
      this.maxEnergy += 3;
      this.energy = this.maxEnergy;
      this.critChance = Math.min(0.4, this.critChance + 0.01);
      (this.scene as any).onPlayerLevelUp?.();
    }
  }

  gainEnergy(amount: number) {
    this.energy = Math.min(this.maxEnergy, this.energy + amount);
  }

  /** Clean up all owned game objects */
  destroy() {
    this.dustEmitter.destroy();
    this.critEmitter.destroy();
    this.slashSprite?.destroy();
    for (const img of this.afterimages) img.destroy();
    this.afterimages = [];
  }

  private die() {
    const gameScene = this.scene as any;
    if (gameScene.onPlayerDeath) {
      gameScene.onPlayerDeath();
    }
  }

  getAttackHitbox(): Phaser.Geom.Rectangle | null {
    if (!this.isAttacking || !this.slashSprite) return null;
    // Hitbox follows the slash sprite position (which arcs)
    const sizes = [
      { w: 22, h: 16 },
      { w: 24, h: 18 },
      { w: 22, h: 16 },
      { w: 30, h: 22 }, // Finisher — large sweep
    ];
    const size = sizes[this.attackCombo];
    return new Phaser.Geom.Rectangle(
      this.slashSprite.x - size.w / 2,
      this.slashSprite.y - size.h / 2,
      size.w, size.h
    );
  }

  /** Check if this attack is a backstab based on enemy position/facing */
  checkBackstab(enemyX: number, enemyFacingRight: boolean): boolean {
    // Backstab: the Wraith is behind the enemy (attacking from the side the enemy is NOT facing)
    const wraithIsRight = this.sprite.x > enemyX;
    // If enemy faces right and wraith is on their left (behind), or vice versa
    this.lastHitWasBackstab = enemyFacingRight !== wraithIsRight;
    return this.lastHitWasBackstab;
  }

  /** Should poison be applied on this attack? (4th combo hit = finisher) */
  shouldApplyPoison(): boolean {
    return this.attackCombo === 3;
  }

  getPoisonParams(): { duration: number; slow: number } {
    return { duration: this.POISON_DURATION, slow: this.POISON_SLOW };
  }

  getAttackDamage(): number {
    const baseDamages = [8, 9, 8, 18]; // Buffed from 6/7/6/14 — still fast, better damage
    let dmg = baseDamages[this.attackCombo];

    // Stat scaling: +3% damage per precision above 5 (Wraith scales on precision)
    const inv = (this.scene as any).getInventory?.();
    if (inv) {
      const precision = inv.getEffectiveStat('precision');
      dmg = Math.round(dmg * (1 + (precision - 5) * 0.03));

      // Skill: meleeDamageBonus (Shadowstrike mastery also gives this)
      const meleeBonus = inv.getSkillEffect('meleeDamageBonus');
      if (meleeBonus) dmg = Math.round(dmg * (1 + meleeBonus));

      // Skill: critDamageBonus — adds to crit multiplier
      const critDmgBonus = inv.getSkillEffect('critDamageBonus') || 0;
      if (this.lastHitWasCrit) {
        dmg = Math.floor(dmg * (this.critMultiplier + critDmgBonus));
      }
    } else {
      if (this.lastHitWasCrit) dmg = Math.floor(dmg * this.critMultiplier);
    }

    // Backstab bonus
    if (this.lastHitWasBackstab) {
      dmg = Math.floor(dmg * this.BACKSTAB_MULTIPLIER);
    }

    return dmg;
  }
}
